### ISSUE TITLE
Why JSON?

### ISSUE THREAD

**Issue by perlancar** [rjbs/String-Flogger#4]
Okay, I have to ask: why JSON? Since this is used for logging framework of Perl application (and dumping Perl data, normally most of the time), wouldn't something like Data::Dumper (or other same-spirit variants) make more sense? Log::Any and Log::Log4perl use Data::Dumper, for example.

The problem with JSON is that it's too limited and loses many details when encoding Perl data, e.g. coderefs, scalar refs, and a bunch other stuffs.

Recently 'dzil build' dies on me when a plugin of mine log_debug() a structure that contains coderefs. Currently my remedy is to patch String::Flogger during runtime so it uses Data::Dmp, e.g.:

```
% PERL5OPT=-MString::Flogger::Patch::UseDataDmp dzil build ... 
```

**Comment by rjbs** [comment]
It's line oriented and easy to parse out of syslogs later by yanking out {{...}} and passing to the zillion of existing JSON processing pipeline tools.  It's also safe to deserialize.  I never, ever need or want to log decompiled code references.

A patch to make `encref` public so that it can be overridden would be okay.

So would a patch to serialize code to something.  (Note that scalar references are already handled.

**Comment by perlancar** [comment]
Some perl dumpers (or configuration of Data::Dumper) are also line oriented (produces one line of dump) and the dump is equally easy (or hard) to yank.

So I guess it depends on the target audience. If a Perl developer is looking at the log she might not want to see compact one-line JSON-encoded data but might prefer a nicely formatted Perl representation of the data structure. A configurable `encref` could be a solution.
